CREATE TABLE IF NOT EXISTS job (
id TEXT PRIMARY KEY,
user_id TEXT NOT NULL,
job_title TEXT NOT NULL,
company TEXT NOT NULL,
job_url TEXT,
job_status TEXT DEFAULT 'applied',
applied_date TEXT DEFAULT CURRENT_DATE,
notes TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_user_id ON job(user_id);
